import json
import logging
from typing import List

from celery import group as celery_group

from app.core.celery_app import celery_app
from app.core.database import SessionLocal
from app.core.outbound.factory import get_insurer_adapter
from app.models.models import (
    SyncLog, Corporate, Employee,
    SyncStatus, PolicyStatus, DeliveryChannel, SyncLogEvent,
)
from app.services.insurer_connector import InsurerConnector, INSURER_API_KEY

logger = logging.getLogger(__name__)

CHUNK_SIZE = 100  # records per Celery worker; tune to worker memory / insurer rate limits

# Terminal statuses: logs in these states must not be reprocessed.
_TERMINAL_STATUSES = {
    SyncStatus.ACTIVE,
    SyncStatus.COMPLETED_OFFLINE,
    SyncStatus.COMPLETED_BOTH,
    SyncStatus.PENDING_OFFLINE,
    SyncStatus.PENDING_BOTH,
    SyncStatus.SOFT_REJECTED,
}


# ---------------------------------------------------------------------------
# Shared audit helper  (defined first — used by both helpers below)
# ---------------------------------------------------------------------------

def record_audit_event_sync(
    db, log_id: int, status: SyncStatus, actor: str, details: dict = None
):
    db.add(SyncLogEvent(
        sync_log_id=log_id,
        event_status=status,
        actor=actor,
        details=details,
    ))


# ---------------------------------------------------------------------------
# _process_single_log
# Pure helper: processes one SyncLog row.  No DB commit — caller commits.
# Designed to run inside process_batch_chunk (fan-out) and is fully isolated:
# exceptions are caught per-record so one bad row never rolls back the chunk.
# ---------------------------------------------------------------------------

def _process_single_log(db, log: SyncLog) -> None:
    # -- Idempotency guard --------------------------------------------------
    # A chunk retry must not re-send records that already reached a terminal
    # state in a previous attempt.
    if log.sync_status in _TERMINAL_STATUSES:
        logger.info(f"Log {log.id} already terminal ({log.sync_status}). Skipping.")
        return

    corporate = db.query(Corporate).filter(Corporate.id == log.corporate_id).first()
    if not corporate:
        logger.warning(f"Log {log.id}: corporate {log.corporate_id} not found. Skipping.")
        return

    log.sync_status = SyncStatus.PROVISIONING
    record_audit_event_sync(db, log.id, SyncStatus.PROVISIONING, "CELERY_CHUNK_WORKER")

    # Fetch the employee so we can keep delivery_status + policy_status in sync.
    emp_code = log.payload.get("employee_code")
    employee = None
    if emp_code:
        employee = db.query(Employee).filter(
            Employee.corporate_id == log.corporate_id,
            Employee.employee_code == emp_code,
        ).first()

    is_addition = log.transaction_type in ("ADDITION", "BATCH_ADDITION")

    # -- OFFLINE channel: file already generated by ingestion endpoint ------
    if corporate.delivery_channel == DeliveryChannel.OFFLINE:
        log.sync_status = SyncStatus.COMPLETED_OFFLINE
        if employee:
            employee.delivery_status = SyncStatus.COMPLETED_OFFLINE
        record_audit_event_sync(
            db, log.id, SyncStatus.COMPLETED_OFFLINE, "CELERY_CHUNK_WORKER",
            {"note": "Batch offline — file already generated by ingestion endpoint"},
        )
        return

    # -- WEBHOOK or BOTH channel: call the insurer --------------------------
    try:
        adapter = get_insurer_adapter(getattr(corporate, "insurer_provider", "standard"))
        final_data = (
            adapter.transform_addition(log.payload)
            if is_addition
            else adapter.transform_deletion(log.payload)
        )
        if isinstance(final_data, dict):
            final_data = json.dumps(final_data)

        headers = adapter.get_headers(api_key=INSURER_API_KEY)
        headers["Idempotency-Key"] = log.transaction_id or str(log.id)

        response_data = InsurerConnector.push_to_insurer_sync(
            data=final_data,
            target_url=corporate.webhook_url,
            headers=headers,
        )
        log.raw_response = response_data

        if corporate.delivery_channel == DeliveryChannel.BOTH:
            # Sent via webhook; still needs the offline file sweep to complete.
            log.sync_status = SyncStatus.PENDING_BOTH
            if employee:
                employee.delivery_status = SyncStatus.PENDING_BOTH
            record_audit_event_sync(
                db, log.id, SyncStatus.PENDING_BOTH, "CELERY_CHUNK_WORKER",
                {"insurer_response": response_data},
            )
        else:
            # Pure webhook — delivery is done; policy issuance is now pending.
            log.sync_status = SyncStatus.ACTIVE
            if employee:
                employee.delivery_status = SyncStatus.ACTIVE
                employee.policy_status = PolicyStatus.PENDING_ISSUANCE
            record_audit_event_sync(
                db, log.id, SyncStatus.ACTIVE, "CELERY_CHUNK_WORKER",
                {"insurer_response": response_data},
            )

    except Exception as exc:
        # Per-record isolation: mark this log as FAILED but let the chunk
        # continue processing the remaining records.
        log.sync_status = SyncStatus.FAILED
        log.error_message = str(exc)
        record_audit_event_sync(
            db, log.id, SyncStatus.FAILED, "CELERY_CHUNK_WORKER",
            {"error": str(exc)},
        )
        logger.error(f"Log {log.id} failed in chunk: {exc}")


# ---------------------------------------------------------------------------
# process_batch_chunk  (Celery task)
# Receives a list of SyncLog IDs, processes each via _process_single_log,
# and commits the whole chunk in one transaction.
# ---------------------------------------------------------------------------

@celery_app.task(
    bind=True,
    max_retries=3,
    autoretry_for=(Exception,),
    retry_backoff=True,
    retry_jitter=True,
)
def process_batch_chunk(self, log_ids: List[int]):
    """
    Fan-out worker.  Receives a chunk of log IDs dispatched by a Celery Group
    from the ingestion endpoint.  One DB session per chunk; one commit at the end.
    """
    db = SessionLocal()
    try:
        logs = db.query(SyncLog).filter(SyncLog.id.in_(log_ids)).all()
        for log in logs:
            _process_single_log(db, log)
        db.commit()
        logger.info(f"Chunk complete: {len(logs)} logs processed.")
        return f"Chunk processed: {len(logs)} records"
    except Exception as exc:
        db.rollback()
        raise exc
    finally:
        db.close()


# ---------------------------------------------------------------------------
# process_sync_event  (Celery task)
# Original single-record task — still used by real-time stream endpoints.
# ---------------------------------------------------------------------------

@celery_app.task(
    bind=True,
    max_retries=5,
    autoretry_for=(Exception,),
    retry_backoff=True,
    retry_jitter=True,
)
def process_sync_event(self, log_id: int):
    """
    Real-time worker.  Processes a single SyncLog, used by stream.py.
    Batch uploads use process_batch_chunk (fan-out) instead.
    """
    db = SessionLocal()
    log = None
    try:
        log = db.query(SyncLog).filter(SyncLog.id == log_id).first()
        if not log:
            return f"Log {log_id} not found"

        # Outbound idempotency: skip if already reached a terminal state.
        if log.sync_status in _TERMINAL_STATUSES:
            logger.info(f"Log {log_id} already processed ({log.sync_status}). Skipping.")
            return f"Already processed: {log.sync_status}"

        corporate = db.query(Corporate).filter(Corporate.id == log.corporate_id).first()

        log.sync_status = SyncStatus.PROVISIONING
        record_audit_event_sync(db, log.id, SyncStatus.PROVISIONING, "CELERY_WORKER")
        db.commit()

        emp_code = log.payload.get("employee_code")
        employee = db.query(Employee).filter(
            Employee.corporate_id == log.corporate_id,
            Employee.employee_code == emp_code,
        ).first()

        is_addition = log.transaction_type in ("ADDITION", "BATCH_ADDITION")
        is_batch = log.transaction_type in ("BATCH_ADDITION", "BATCH_DELETION")

        # -- Route by delivery channel --------------------------------------
        if corporate.delivery_channel in (DeliveryChannel.WEBHOOK, DeliveryChannel.BOTH):
            try:
                adapter = get_insurer_adapter(
                    getattr(corporate, "insurer_provider", "standard")
                )
                final_data = (
                    adapter.transform_addition(log.payload)
                    if is_addition
                    else adapter.transform_deletion(log.payload)
                )
                if isinstance(final_data, dict):
                    final_data = json.dumps(final_data)

                headers = adapter.get_headers(api_key=INSURER_API_KEY)
                headers["Idempotency-Key"] = log.transaction_id or str(log.id)

                response_data = InsurerConnector.push_to_insurer_sync(
                    data=final_data,
                    target_url=corporate.webhook_url,
                    headers=headers,
                )
                log.raw_response = response_data

                if corporate.delivery_channel == DeliveryChannel.BOTH:
                    log.sync_status = SyncStatus.PENDING_BOTH
                    if employee:
                        employee.delivery_status = SyncStatus.PENDING_BOTH
                    record_audit_event_sync(
                        db, log.id, SyncStatus.PENDING_BOTH, "CELERY_WORKER",
                        {"insurer_response": response_data},
                    )
                else:
                    log.sync_status = SyncStatus.ACTIVE
                    if employee:
                        employee.delivery_status = SyncStatus.ACTIVE
                        employee.policy_status = PolicyStatus.PENDING_ISSUANCE
                    record_audit_event_sync(
                        db, log.id, SyncStatus.ACTIVE, "CELERY_WORKER",
                        {"insurer_response": response_data},
                    )

            except Exception as exc:
                log.retry_count += 1
                log.error_message = str(exc)
                record_audit_event_sync(
                    db, log.id, SyncStatus.FAILED, "CELERY_WORKER",
                    {"error": str(exc), "attempt": log.retry_count},
                )
                db.commit()
                raise self.retry(exc=exc)

        elif corporate.delivery_channel == DeliveryChannel.OFFLINE:
            if is_batch:
                log.sync_status = SyncStatus.COMPLETED_OFFLINE
                if employee:
                    employee.delivery_status = SyncStatus.COMPLETED_OFFLINE
                record_audit_event_sync(
                    db, log.id, SyncStatus.COMPLETED_OFFLINE, "CELERY_WORKER",
                    {"note": "Batch processed immediately"},
                )
            else:
                log.sync_status = SyncStatus.PENDING_OFFLINE
                if employee:
                    employee.delivery_status = SyncStatus.PENDING_OFFLINE
                record_audit_event_sync(
                    db, log.id, SyncStatus.PENDING_OFFLINE, "CELERY_WORKER",
                    {"note": "Parked for sweeper"},
                )

        db.commit()
        return f"Processed log {log_id} successfully"

    except Exception as exc:
        db.rollback()
        if log:
            log.sync_status = SyncStatus.FAILED
            log.error_message = str(exc)
            db.commit()
        logger.error(f"Task failed for log {log_id}: {exc}")
        record_audit_event_sync(
            db, log.id, SyncStatus.FAILED, "CELERY_WORKER_CRASH", {"error": str(exc)}
        )
        raise exc
    finally:
        db.close()
