import json
import logging
from types import SimpleNamespace
from typing import List, Optional

from celery import group as celery_group

from app.core.celery_app import celery_app
from app.core.database import SessionLocal
from app.core.cache import cache_get, cache_set, CORPORATE_TTL
from app.core.outbound.factory import get_insurer_adapter
from app.models.models import (
    SyncLog, Corporate, Employee,
    SyncStatus, PolicyStatus, DeliveryChannel, SyncLogEvent,
)
from app.services.insurer_connector import InsurerConnector, INSURER_API_KEY

logger = logging.getLogger(__name__)

CHUNK_SIZE = 100  # records per Celery worker; tune to worker memory / insurer rate limits

# Terminal statuses: logs in these states must not be reprocessed.
_TERMINAL_STATUSES = {
    SyncStatus.ACTIVE,
    SyncStatus.COMPLETED_OFFLINE,
    SyncStatus.COMPLETED_BOTH,
    SyncStatus.PENDING_OFFLINE,
    SyncStatus.PENDING_BOTH,
    SyncStatus.SOFT_REJECTED,
}


# ---------------------------------------------------------------------------
# Corporate cache helpers  (sync Redis — DB 1)
# ---------------------------------------------------------------------------

def _corporate_to_dict(c: Corporate) -> dict:
    return {
        "id": c.id,
        "name": c.name,
        "broker_id": c.broker_id,
        "webhook_url": c.webhook_url,
        "insurer_format": getattr(c, "insurer_format", "json"),
        "delivery_channel": c.delivery_channel.value if c.delivery_channel else None,
        "base_folder": getattr(c, "base_folder", ""),
        "insurer_provider": getattr(c, "insurer_provider", "standard"),
        "hrms_provider": getattr(c, "hrms_provider", "standard"),
    }


def _dict_to_corporate(d: dict) -> SimpleNamespace:
    corp = SimpleNamespace(**d)
    if d.get("delivery_channel"):
        corp.delivery_channel = DeliveryChannel(d["delivery_channel"])
    return corp


def _get_corporate(db, corporate_id: str) -> Optional[SimpleNamespace]:
    """
    Fetch corporate by id. Checks Redis first; falls back to DB on miss.
    Writes through to cache on DB hit.
    """
    cache_key = f"ins:corp:{corporate_id}"
    cached = cache_get(cache_key)
    if cached:
        return _dict_to_corporate(cached)

    corporate = db.query(Corporate).filter(Corporate.id == corporate_id).first()
    if corporate:
        cache_set(cache_key, _corporate_to_dict(corporate), CORPORATE_TTL)
    return corporate


# ---------------------------------------------------------------------------
# Shared audit helper  (defined first — used by both helpers below)
# ---------------------------------------------------------------------------

def record_audit_event_sync(
    db, log_id: int, status: SyncStatus, actor: str,
    details: dict = None, policy_status: str = None
):
    db.add(SyncLogEvent(
        sync_log_id=log_id,
        event_status=status,
        actor=actor,
        details=details,
        policy_status=policy_status,
    ))


# ---------------------------------------------------------------------------
# _process_single_log
# Pure helper: processes one SyncLog row.  No DB commit — caller commits.
# Designed to run inside process_batch_chunk (fan-out) and is fully isolated:
# exceptions are caught per-record so one bad row never rolls back the chunk.
# ---------------------------------------------------------------------------

def _process_single_log(db, log: SyncLog) -> None:
    # -- Idempotency guard --------------------------------------------------
    # A chunk retry must not re-send records that already reached a terminal
    # state in a previous attempt.
    if log.sync_status in _TERMINAL_STATUSES:
        logger.info(f"Log {log.id} already terminal ({log.sync_status}). Skipping.")
        return

    corporate = _get_corporate(db, log.corporate_id)
    if not corporate:
        logger.warning(f"Log {log.id}: corporate {log.corporate_id} not found. Skipping.")
        return

    # Fetch the employee BEFORE marking PROVISIONING so we can snapshot
    # the existing policy_status for the audit trail.
    emp_code = log.payload.get("employee_code")
    employee = None
    if emp_code:
        employee = db.query(Employee).filter(
            Employee.corporate_id == log.corporate_id,
            Employee.employee_code == emp_code,
        ).first()

    pre_ps = None
    if employee and employee.policy_status:
        ps = employee.policy_status
        pre_ps = ps.value if hasattr(ps, "value") else str(ps)

    log.sync_status = SyncStatus.PROVISIONING
    record_audit_event_sync(db, log.id, SyncStatus.PROVISIONING, "CELERY_CHUNK_WORKER",
                            policy_status=pre_ps)

    is_deletion = log.transaction_type in ("DELETION", "BATCH_DELETION")
    is_addition = not is_deletion  # ADDITION, UPDATE, BATCH_ADDITION all use transform_addition

    # -- OFFLINE channel: file already generated by ingestion endpoint ------
    if corporate.delivery_channel == DeliveryChannel.OFFLINE:
        ps_value = PolicyStatus.LAPSED.value if is_deletion else None
        log.sync_status = SyncStatus.COMPLETED_OFFLINE
        if ps_value:
            log.policy_status = ps_value
        if employee:
            employee.delivery_status = SyncStatus.COMPLETED_OFFLINE
            if is_deletion:
                employee.policy_status = PolicyStatus.LAPSED
        record_audit_event_sync(
            db, log.id, SyncStatus.COMPLETED_OFFLINE, "CELERY_CHUNK_WORKER",
            {"note": "Batch offline — file already generated by ingestion endpoint"},
            policy_status=ps_value,
        )
        return

    # -- WEBHOOK or BOTH channel: call the insurer --------------------------
    try:
        adapter = get_insurer_adapter(getattr(corporate, "insurer_provider", "standard"))
        final_data = (
            adapter.transform_addition(log.payload)
            if is_addition
            else adapter.transform_deletion(log.payload)
        )
        if isinstance(final_data, dict):
            final_data = json.dumps(final_data)

        headers = adapter.get_headers(api_key=INSURER_API_KEY)
        headers["Idempotency-Key"] = log.transaction_id or str(log.id)

        response_data = InsurerConnector.push_to_insurer_sync(
            data=final_data,
            target_url=corporate.webhook_url,
            headers=headers,
        )
        log.raw_response = response_data

        new_policy_status = PolicyStatus.LAPSED if is_deletion else PolicyStatus.PENDING_ISSUANCE
        ps_value = new_policy_status.value

        if corporate.delivery_channel == DeliveryChannel.BOTH:
            log.sync_status = SyncStatus.PENDING_BOTH
            log.policy_status = ps_value
            if employee:
                employee.delivery_status = SyncStatus.PENDING_BOTH
                employee.policy_status = new_policy_status
            record_audit_event_sync(
                db, log.id, SyncStatus.PENDING_BOTH, "CELERY_CHUNK_WORKER",
                {"insurer_response": response_data}, policy_status=ps_value,
            )
        else:
            log.sync_status = SyncStatus.ACTIVE
            log.policy_status = ps_value
            if employee:
                employee.delivery_status = SyncStatus.ACTIVE
                employee.policy_status = new_policy_status
            record_audit_event_sync(
                db, log.id, SyncStatus.ACTIVE, "CELERY_CHUNK_WORKER",
                {"insurer_response": response_data}, policy_status=ps_value,
            )

    except Exception as exc:
        # Per-record isolation: mark this log as FAILED but let the chunk
        # continue processing the remaining records.
        log.sync_status = SyncStatus.FAILED
        log.error_message = str(exc)
        record_audit_event_sync(
            db, log.id, SyncStatus.FAILED, "CELERY_CHUNK_WORKER",
            {"error": str(exc)},
        )
        logger.error(f"Log {log.id} failed in chunk: {exc}")


# ---------------------------------------------------------------------------
# process_batch_chunk  (Celery task)
# Receives a list of SyncLog IDs, processes each via _process_single_log,
# and commits the whole chunk in one transaction.
# ---------------------------------------------------------------------------

@celery_app.task(
    bind=True,
    max_retries=3,
    autoretry_for=(Exception,),
    retry_backoff=True,
    retry_jitter=True,
)
def process_batch_chunk(self, log_ids: List[int]):
    """
    Fan-out worker.  Receives a chunk of log IDs dispatched by a Celery Group
    from the ingestion endpoint.  One DB session per chunk; one commit at the end.
    """
    db = SessionLocal()
    try:
        logs = db.query(SyncLog).filter(SyncLog.id.in_(log_ids)).all()
        for log in logs:
            _process_single_log(db, log)
        db.commit()
        logger.info(f"Chunk complete: {len(logs)} logs processed.")
        return f"Chunk processed: {len(logs)} records"
    except Exception as exc:
        db.rollback()
        raise exc
    finally:
        db.close()


# ---------------------------------------------------------------------------
# process_sync_event  (Celery task)
# Original single-record task — still used by real-time stream endpoints.
# ---------------------------------------------------------------------------

@celery_app.task(
    bind=True,
    max_retries=5,
    autoretry_for=(Exception,),
    retry_backoff=True,
    retry_jitter=True,
)
def process_sync_event(self, log_id: int):
    """
    Real-time worker.  Processes a single SyncLog, used by stream.py.
    Batch uploads use process_batch_chunk (fan-out) instead.
    """
    db = SessionLocal()
    log = None
    try:
        log = db.query(SyncLog).filter(SyncLog.id == log_id).first()
        if not log:
            return f"Log {log_id} not found"

        # Outbound idempotency: skip if already reached a terminal state.
        if log.sync_status in _TERMINAL_STATUSES:
            logger.info(f"Log {log_id} already processed ({log.sync_status}). Skipping.")
            return f"Already processed: {log.sync_status}"

        corporate = _get_corporate(db, log.corporate_id)

        # Fetch employee BEFORE PROVISIONING to snapshot existing policy_status.
        emp_code = log.payload.get("employee_code")
        employee = db.query(Employee).filter(
            Employee.corporate_id == log.corporate_id,
            Employee.employee_code == emp_code,
        ).first()

        pre_ps = None
        if employee and employee.policy_status:
            ps = employee.policy_status
            pre_ps = ps.value if hasattr(ps, "value") else str(ps)

        log.sync_status = SyncStatus.PROVISIONING
        record_audit_event_sync(db, log.id, SyncStatus.PROVISIONING, "CELERY_WORKER",
                                policy_status=pre_ps)
        db.commit()

        is_deletion = log.transaction_type in ("DELETION", "BATCH_DELETION")
        is_addition = not is_deletion  # ADDITION, UPDATE, BATCH_ADDITION all use transform_addition
        is_batch = log.transaction_type in ("BATCH_ADDITION", "BATCH_DELETION")

        new_policy_status = PolicyStatus.LAPSED if is_deletion else PolicyStatus.PENDING_ISSUANCE
        ps_value = new_policy_status.value

        # -- Route by delivery channel --------------------------------------
        if corporate.delivery_channel in (DeliveryChannel.WEBHOOK, DeliveryChannel.BOTH):
            try:
                adapter = get_insurer_adapter(
                    getattr(corporate, "insurer_provider", "standard")
                )
                final_data = (
                    adapter.transform_addition(log.payload)
                    if is_addition
                    else adapter.transform_deletion(log.payload)
                )
                if isinstance(final_data, dict):
                    final_data = json.dumps(final_data)

                headers = adapter.get_headers(api_key=INSURER_API_KEY)
                headers["Idempotency-Key"] = log.transaction_id or str(log.id)

                response_data = InsurerConnector.push_to_insurer_sync(
                    data=final_data,
                    target_url=corporate.webhook_url,
                    headers=headers,
                )
                log.raw_response = response_data

                if corporate.delivery_channel == DeliveryChannel.BOTH:
                    log.sync_status = SyncStatus.PENDING_BOTH
                    log.policy_status = ps_value
                    if employee:
                        employee.delivery_status = SyncStatus.PENDING_BOTH
                        employee.policy_status = new_policy_status
                    record_audit_event_sync(
                        db, log.id, SyncStatus.PENDING_BOTH, "CELERY_WORKER",
                        {"insurer_response": response_data}, policy_status=ps_value,
                    )
                else:
                    log.sync_status = SyncStatus.ACTIVE
                    log.policy_status = ps_value
                    if employee:
                        employee.delivery_status = SyncStatus.ACTIVE
                        employee.policy_status = new_policy_status
                    record_audit_event_sync(
                        db, log.id, SyncStatus.ACTIVE, "CELERY_WORKER",
                        {"insurer_response": response_data}, policy_status=ps_value,
                    )

            except Exception as exc:
                log.retry_count += 1
                log.error_message = str(exc)
                record_audit_event_sync(
                    db, log.id, SyncStatus.FAILED, "CELERY_WORKER",
                    {"error": str(exc), "attempt": log.retry_count},
                )
                db.commit()
                raise self.retry(exc=exc)

        elif corporate.delivery_channel == DeliveryChannel.OFFLINE:
            offline_ps = PolicyStatus.LAPSED.value if is_deletion else None
            if is_batch:
                log.sync_status = SyncStatus.COMPLETED_OFFLINE
                if offline_ps:
                    log.policy_status = offline_ps
                if employee:
                    employee.delivery_status = SyncStatus.COMPLETED_OFFLINE
                    if is_deletion:
                        employee.policy_status = PolicyStatus.LAPSED
                record_audit_event_sync(
                    db, log.id, SyncStatus.COMPLETED_OFFLINE, "CELERY_WORKER",
                    {"note": "Batch processed immediately"}, policy_status=offline_ps,
                )
            else:
                log.sync_status = SyncStatus.PENDING_OFFLINE
                if offline_ps:
                    log.policy_status = offline_ps
                if employee:
                    employee.delivery_status = SyncStatus.PENDING_OFFLINE
                    if is_deletion:
                        employee.policy_status = PolicyStatus.LAPSED
                record_audit_event_sync(
                    db, log.id, SyncStatus.PENDING_OFFLINE, "CELERY_WORKER",
                    {"note": "Parked for sweeper"}, policy_status=offline_ps,
                )

        db.commit()
        return f"Processed log {log_id} successfully"

    except Exception as exc:
        db.rollback()
        if log:
            log.sync_status = SyncStatus.FAILED
            log.error_message = str(exc)
            db.commit()
        logger.error(f"Task failed for log {log_id}: {exc}")
        record_audit_event_sync(
            db, log.id, SyncStatus.FAILED, "CELERY_WORKER_CRASH", {"error": str(exc)}
        )
        raise exc
    finally:
        db.close()
