"""add_syn_log_events

Revision ID: 365001e83183
Revises: 53849444a78c
Create Date: 2026-03-02 15:56:49.320767

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '365001e83183'
down_revision: Union[str, Sequence[str], None] = '53849444a78c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sync_log_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('sync_log_id', sa.Integer(), nullable=True),
    sa.Column('event_status', sa.Enum('PENDING', 'PROVISIONING', 'ACTIVE', 'FAILED', 'COMPLETED_OFFLINE', 'PENDING_OFFLINE', 'COMPLETED_BOTH', 'PENDING_BOTH', name='syncstatus'), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['sync_log_id'], ['sync_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sync_log_events_sync_log_id'), 'sync_log_events', ['sync_log_id'], unique=False)
    op.add_column('sync_logs', sa.Column('source', sa.Enum('ONLINE', 'BATCH', name='syncsource'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_logs', 'source')
    op.drop_index(op.f('ix_sync_log_events_sync_log_id'), table_name='sync_log_events')
    op.drop_table('sync_log_events')
    # ### end Alembic commands ###
