"""add_broker_review_pending_and_pending_dispatch_enums

Revision ID: 4127433ba992
Revises: c1d2e3f4a5b6
Create Date: 2026-03-06 14:11:21.856172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4127433ba992'
down_revision: Union[str, Sequence[str], None] = 'c1d2e3f4a5b6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # PostgreSQL enum values are append-only — ADD VALUE is non-transactional,
    # so we use op.execute() directly.
    op.execute("ALTER TYPE syncstatus ADD VALUE IF NOT EXISTS 'BROKER_REVIEW_PENDING'")
    op.execute("ALTER TYPE policystatus ADD VALUE IF NOT EXISTS 'PENDING_DISPATCH'")

    # api_keys.scope nullable change (autogenerated, safe to keep)
    op.alter_column('api_keys', 'scope',
               existing_type=postgresql.ENUM('CORPORATE', 'BROKER', name='apikeyscope'),
               nullable=True,
               existing_server_default=sa.text("'CORPORATE'::apikeyscope"))


def downgrade() -> None:
    """Downgrade schema."""
    # Enum values cannot be removed in PostgreSQL without recreating the type.
    # Revert only the api_keys nullable change; leave the enum values in place.
    op.alter_column('api_keys', 'scope',
               existing_type=postgresql.ENUM('CORPORATE', 'BROKER', name='apikeyscope'),
               nullable=False,
               existing_server_default=sa.text("'CORPORATE'::apikeyscope"))
