"""add_insurer_provider_to_corporates

Revision ID: 53849444a78c
Revises: a1ade4c00d5d
Create Date: 2026-02-28 20:08:52.953502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53849444a78c'
down_revision: Union[str, Sequence[str], None] = 'a1ade4c00d5d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporates', sa.Column('insurer_provider', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporates', 'insurer_provider')
    # ### end Alembic commands ###
