"""add_hrms_provider_to_corporates

Revision ID: a1ade4c00d5d
Revises: c88c67afe6df
Create Date: 2026-02-28 18:13:03.117754

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a1ade4c00d5d'
down_revision: Union[str, Sequence[str], None] = 'c88c67afe6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('corporates', sa.Column('hrms_provider', sa.String(), server_default='standard', nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('corporates', 'hrms_provider')
    # ### end Alembic commands ###
