"""add_joining_and_leaving_dates

Revision ID: bf3c7e3d594a
Revises: f78ff425daf2
Create Date: 2026-02-27 17:28:31.435319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf3c7e3d594a'
down_revision: Union[str, Sequence[str], None] = 'f78ff425daf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('employees', sa.Column('date_of_joining', sa.Date(), nullable=True))
    op.add_column('employees', sa.Column('date_of_leaving', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('employees', 'date_of_leaving')
    op.drop_column('employees', 'date_of_joining')
    # ### end Alembic commands ###
