"""add_transaction_id_to_sync_logs

Revision ID: c88c67afe6df
Revises: bf3c7e3d594a
Create Date: 2026-02-27 18:00:03.029553

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c88c67afe6df'
down_revision: Union[str, Sequence[str], None] = 'bf3c7e3d594a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sync_logs', sa.Column('transaction_id', sa.String(), nullable=True))
    op.create_index(op.f('ix_sync_logs_transaction_id'), 'sync_logs', ['transaction_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sync_logs_transaction_id'), table_name='sync_logs')
    op.drop_column('sync_logs', 'transaction_id')
    # ### end Alembic commands ###
