"""add_corporate_storage_and_sync_fields

Revision ID: f78ff425daf2
Revises: 54c7e124db7b
Create Date: 2026-02-26 17:46:51.376605

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78ff425daf2'
down_revision: Union[str, Sequence[str], None] = '54c7e124db7b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    delivery_channel_enum = sa.Enum('WEBHOOK', 'OFFLINE', 'BOTH', name='deliverychannel')
    sync_status_enum = sa.Enum('PENDING', 'PROVISIONING', 'ACTIVE', 'FAILED', 'COMPLETED_OFFLINE', name='syncstatus')

    delivery_channel_enum.create(op.get_bind(), checkfirst=True)
    sync_status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('corporates', sa.Column('delivery_channel', sa.Enum('WEBHOOK', 'OFFLINE', 'BOTH', name='deliverychannel'), nullable=True))
    op.add_column('corporates', sa.Column('base_folder', sa.String(), nullable=True))
    op.add_column('corporates', sa.Column('last_report_path', sa.String(), nullable=True))
    op.add_column('employees', sa.Column('sync_status', sa.Enum('PENDING', 'PROVISIONING', 'ACTIVE', 'FAILED', 'COMPLETED_OFFLINE', name='syncstatus'), nullable=True))
    op.add_column('sync_logs', sa.Column('sync_status', sa.Enum('PENDING', 'PROVISIONING', 'ACTIVE', 'FAILED', 'COMPLETED_OFFLINE', name='syncstatus'), nullable=True))
    op.add_column('sync_logs', sa.Column('retry_count', sa.Integer(), nullable=True))
    op.add_column('sync_logs', sa.Column('max_retries', sa.Integer(), nullable=True))
    op.add_column('sync_logs', sa.Column('raw_response', sa.JSON(), nullable=True))
    op.add_column('sync_logs', sa.Column('error_message', sa.String(), nullable=True))
    op.add_column('sync_logs', sa.Column('file_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sync_logs', 'file_path')
    op.drop_column('sync_logs', 'error_message')
    op.drop_column('sync_logs', 'raw_response')
    op.drop_column('sync_logs', 'max_retries')
    op.drop_column('sync_logs', 'retry_count')
    op.drop_column('sync_logs', 'sync_status')
    op.drop_column('employees', 'sync_status')
    op.drop_column('corporates', 'last_report_path')
    op.drop_column('corporates', 'base_folder')
    op.drop_column('corporates', 'delivery_channel')

    sa.Enum(name='deliverychannel').drop(op.get_bind(), checkfirst=True)
    sa.Enum(name='syncstatus').drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
